name: CHreative
favicon: null
layout_spectrum: 0.14683222607709467
typography_spectrum: 0.40046461927704513
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.18383502634242177
  lightness: 0.4322341026272625
  saturation: 0.9854474095627666
  rhythmicContrast: 0.6582764415070415
purpose: []
